In [130]:
# Traditional Python list
temps_list = [72, 75, 68, 71, 74, 69, 73]
# Convert to NumPy array
import numpy as np
temps_array = np.array([72, 75, 68, 71, 74, 69, 73])
print(temps_array)
print(type(temps_array))

[72 75 68 71 74 69 73]
<class 'numpy.ndarray'>


In [131]:
# Temperatures from 3 sensors over 5 days
sensor_temps = np.array([
 [72, 70, 71], # Day 1
 [75, 73, 74], # Day 2
 [68, 67, 69], # Day 3
 [71, 70, 72], # Day 4
 [74, 72, 73] # Day 5
])
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")


[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [132]:
# Array of zeros (5x3)
zeros = np.zeros((5, 3))
# Array of ones (5x3)
ones = np.ones((5, 3))
# Identity matrix (3x3)
identity = np.eye(3)
# Range of values
sequence = np.arange(0, 10, 2)
# Evenly spaced values
linspace = np.linspace(0, 100, 5)


In [133]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(2, 3)
6


In [134]:
arr = np.array([1.5, 2.7, 3.2])
print(arr.dtype)

float64


In [135]:
arr = np.array([1,2,3])
print(arr.itemsize)

8


In [136]:
# Soil pH readings (3 fields × 4 samples)
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
# Single element: row 1, column 2
print("Single element: row 1, column 2=",ph_levels[1, 2])
# Entire row 0
print("Entire row 0=",ph_levels[0, :])
# Entire column 3
print("Entire column 3=",ph_levels[:, 3])
# First 2 rows, first 3 columns
sub_array = ph_levels[0:2, 0:3]
print("First 2 rows, first 3 columns=",sub_array)
# Every other row, all columns
print("Every other row, all columns=",ph_levels[::2, :])

Single element: row 1, column 2= 6.9
Entire row 0= [6.5 6.8 6.3 6.7]
Entire column 3= [6.7 7.2 6.3]
First 2 rows, first 3 columns= [[6.5 6.8 6.3]
 [7.1 7.  6.9]]
Every other row, all columns= [[6.5 6.8 6.3 6.7]
 [6.2 6.4 6.1 6.3]]


In [137]:
temperatures = np.array([72, 85, 91, 68, 95, 70, 88])
# Create a boolean array (mask)
hot_days = temperatures > 85
print("hot_days=",hot_days)
# Use mask to filter original array
print("hot days=",temperatures[hot_days])
# Can do it in one line
print("hot days=",temperatures[temperatures > 85])
# Combine conditions with & (and), | (or)
moderate = temperatures[(temperatures >= 70) &
(temperatures <= 85)]
print(f"moderate={moderate}")
# Find extreme values (very hot OR very cold)
extreme = temperatures[(temperatures > 90)|(temperatures < 70)]
print(f"extreme={extreme}")

hot_days= [False False  True False  True False  True]
hot days= [91 95 88]
hot days= [91 95 88]
moderate=[72 85 70]
extreme=[91 68 95]


In [140]:
# Crop yields in tons
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138, 132])
total_yield = field_a + field_b
print("total_yield =",total_yield)
difference = field_a - field_b
print("difference =",difference)
doubled = field_a * 2
print("doubled=",doubled)



total_yield = [238 275 280 260]
difference = [ 2 -5  4 -4]
doubled= [240 270 284 256]


In [139]:
# Python list approach (slow!)
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138, 132])
result = []
for i in range(len(field_a)):
 result.append(field_a[i] + field_b[i])
 print(result)


[np.int64(238)]
[np.int64(238), np.int64(275)]
[np.int64(238), np.int64(275), np.int64(280)]
[np.int64(238), np.int64(275), np.int64(280), np.int64(260)]
